### ISSUE TITLE
각 다중이용시설의 데이터 양이 더 많았으면 좋겠습니다

### ISSUE THREAD

**Issue by limetry2392** [ClustProject/KWTAppDataServer#1]
각 다중이용시설들의 데이터양이 더 많았으면 좋겠습니다

**Comment by kimjuhoe1021** [comment]
안녕하세요
현재 데이터의 기간 한정으로 업로드 한 건으로
아래 메일로 문의 주시면
상담드리겠습니다.
khelp@kweather.co.kr

감사합니다.
