### ISSUE TITLE
SDOT

### ISSUE THREAD

**Issue by JoenSooJoeng** [ClustProject/KWTAppDataServer#12]
SDOT이 무엇인가요?

**Comment by sunkyong** [comment]
SDOT은 스마스서울 도시데이터센서를 의미합니다.
해당 repository에서는 케이웨더의 IoT 공기질 측정기 기반 스마트서울 도시데이터 센서 환경정보를 제공합니다.
간단히 말해 실외공기질 측정 데이터입니다.
