### ISSUE TITLE
폴더명

### ISSUE THREAD

**Issue by JoenSooJoeng** [ClustProject/KWTAppDataServer#13]
폴더명을 IAQ 대신 Indoor Air Quality, SDOT 대신 Outdoor Air Quality라고 써주시는 것이 더 명확할 듯 합니다.

**Comment by sunkyong** [comment]
폴더명 변경 완료하였습니다. 감사합니다!

**Comment by sunkyong** [comment]
폴더명 변경 완료하였습니다. 감사합니다!
